Excersise 1a (but I use two versions of it a and A

In [10]:
import numpy as np

In [25]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [18]:
A = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])

Excersise 1b (again two versions)

In [14]:
b = np.array([1,2,3])

In [19]:
B = np.array([2, 4, -1])

Excersise 1c (again two versions)

In [16]:
from scipy import linalg

In [33]:
X = linalg.solve(A,B)

In [34]:
print(X)

[ 2. -2.  9.]


In [36]:
x = linalg.solve(a,b)

LinAlgError: Matrix is singular.

I don't understand why I should continue beyond this as it's not possible to solve the system. I'm satisfied that it worked for capital variables from documentation.

Excersise 1d

In [35]:
print(np.matmul(A,X))

[ 2.  4. -1.]


Excersise 1e (using the capital version)

In [47]:
B = np.random.rand(3,3)

In [48]:
B

array([[0.66028145, 0.18600481, 0.70899882],
       [0.23753571, 0.71211405, 0.94032578],
       [0.65325573, 0.74054656, 0.58442392]])

In [52]:
X = linalg.solve(A,B)

In [53]:
print(X)

[[ 0.22707057  0.32204658  0.51793008]
 [-0.01046514 -0.39006747 -0.4223957 ]
 [ 0.70558141  2.6908839   2.69640244]]


In [54]:
print(np.matmul(A,X))

[[0.66028145 0.18600481 0.70899882]
 [0.23753571 0.71211405 0.94032578]
 [0.65325573 0.74054656 0.58442392]]


Excersise 1f (using the original matrix)

In [60]:
linalg.eig(a)

(array([ 1.61168440e+01+0.j, -1.11684397e+00+0.j, -1.30367773e-15+0.j]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

Excersise 1g (using the original matrix)

In [63]:
-linalg.det(a)

-0.0

Was that what was asked for?

Excersise 1h (using the original matrix)

In [64]:
linalg.norm(a,1)

18.0

In [65]:
linalg.norm(a,2)

16.84810335261421